---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: echo
  project: default
  sources:
    - repoURL: https://github.com/prrlvr/infra.git
      targetRevision: HEAD
      path: kubernetes/apps/k3s/echo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true