---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@prrlvr.fr
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        webhook:
          groupName: acme.prrlvr.fr
          solverName: ovh
          config:
            endpoint: ovh-eu
            applicationKey: bed6ec49350eee56
            applicationSecretRef:
              key: application_secret
              name: ovh-credentials
            consumerKey: 0b0886a2eb553e513866967319155981