---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgres-superuser
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: postgres-superuser
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
  data:
    - secretKey: username
      remoteRef:
        key: postgres/superuser
        property: username
    - secretKey: password
      remoteRef:
        key: postgres/superuser
        property: password

