---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: ilo-exporter-config
  namespace: monitoring
  labels:
    prometheus: system-monitoring-prometheus
spec:
  staticConfigs:
    - labels:
        job: ilo
      targets:
        - ilo-exporter.monitoring.svc.cluster.local:9090
  scrapeInterval: 300s
  scrapeTimeout: 120s
  params:
    host: 
    - "10.0.40.201"
  metricRelabelings:
    - sourceLabels:
      - "__address__"
      targetLabel: "__param_host"
    - sourceLabels:
      - "__param_host"
      targetLabel: "instance"
      replacement: '${1}'
    - targetLabel: "__address__"
      replacement: ilo-exporter.monitoring.svc.cluster.local