---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgadmin-creds
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: pgadmin-creds
  data:
    - secretKey: email
      remoteRef:
        key: pgadmin/pgadmin
        property: username
    - secretKey: password
      remoteRef:
        key: pgadmin/pgadmin
        property: password