---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ilo-metrics-creds
spec:
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: ilo-metrics-creds
  data:
    - secretKey: username
      remoteRef:
        key: observability/ilo-metrics-creds
        property: username
    - secretKey: password
      remoteRef:
        key: observability/ilo-metrics-creds
        property: password