---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: kube-system
  project: default
  sources:
    - repoURL: https://coredns.github.io/helm
      chart: coredns
      targetRevision: 1.39.2
      helm:
        releaseName: coredns
        values: |
          replicaCount: 2
          hpa:
            enabled: true
            minReplicas: 2
            maxReplicas: 10
            metrics:
              - type: Resource
                resource:
                  name: memory
                  target:
                    type: Utilization
                    averageUtilization: 60
              - type: Resource
                resource:
                  name: cpu
                  target:
                    type: Utilization
                    averageUtilization: 60
          # prometheus:
          #   service:
          #     enabled: true
          #   monitor:
          #     enabled: true
          servers:
            - zones:
              - zone: .
              port: 53
              plugins:
              - name: errors
              # Serves a /health endpoint on :8080, required for livenessProbe
              - name: health
                configBlock: |-
                  lameduck 5s
              # Serves a /ready endpoint on :8181, required for readinessProbe
              - name: ready
              # Required to query kubernetes API for data
              - name: kubernetes
                # parameters: k8s.prrlvr.local in-addr.arpa ip6.arpa
                parameters: cluster.local in-addr.arpa ip6.arpa
                configBlock: |-
                  pods insecure
                  fallthrough in-addr.arpa ip6.arpa
                  ttl 30
              # Serves a /metrics endpoint on :9153, required for serviceMonitor
              - name: prometheus
                parameters: 0.0.0.0:9153
              - name: forward
                parameters: . /etc/resolv.conf
              - name: cache
                parameters: 30
              - name: loop
              - name: reload
              - name: loadbalance
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
