# yamllint disable rule:line-length
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: ingress-nginx
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: 4.12.0
      helm:
        releaseName: ingress-nginx
        values: |
          controller:
            hostNetwork: true
            service:
              type: ""
            replicaCount: 2
            minAvailable: 1
            allowSnippetAnnotations: true
            publishService:
              enabled: false
            config:
              use-geoip: "false"
              use-geoip2: "false"
              proxy-buffer-size: "16k"
              annotations-risk-level: "Critical"
              strict-validate-path-type: "false"
            extraArgs:
              publish-status-address: 93.31.83.49
              enable-ssl-passthrough: true
          defaultBackend:
            enabled: true
            replicaCount: 1
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true