---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-nfs-provider
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: storage
  project: default
  sources:
    - repoURL: https://github.com/prrlvr/infra.git
      targetRevision: HEAD
      path: kubernetes/apps/k8s/democratic-csi
    - repoURL: https://democratic-csi.github.io/charts/
      chart: democratic-csi
      targetRevision: 0.14.7
      helm:
        values: |
            csiDriver:
              name: "democratic-csi.nfs"
              fsGroupPolicy: File

            storageClasses:
              - name: freenas-nfs-csi
                defaultClass: true
                reclaimPolicy: Retain
                volumeBindingMode: Immediate
                allowVolumeExpansion: true
                parameters:
                  fsType: nfs
                mountOptions:
                  - noatime
                  - nfsvers=4
                secrets:
                  provisioner-secret:
                  controller-publish-secret:
                  node-stage-secret:
                  node-publish-secret:
                  controller-expand-secret:
            volumeSnapshotClasses: []
            driver:
              config:
                driver: freenas-nfs
                instance_id:
                httpConnection:
                  protocol: http
                  host: 10.0.40.9
                  port: 80
                  apiKey: 1-EJntADFYt0hB3H47h3Y0KSyFLLR5aoeuc25yVqhcWipCAjepMErz8YyS1ZZ1oBep
                  allowInsecure: true
                sshConnection:
                  host: 10.0.40.9
                  port: 22
                  username: root
                  password: passacaglia
                zfs:
                  # can be used to override defaults if necessary
                  # the example below is useful for TrueNAS 12
                  #cli:
                  #  sudoEnabled: true
                  #
                  #  leave paths unset for auto-detection
                  #  paths:
                  #    zfs: /usr/local/sbin/zfs
                  #    zpool: /usr/local/sbin/zpool
                  #    sudo: /usr/local/bin/sudo
                  #    chroot: /usr/sbin/chroot
                  datasetProperties: 
                    "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
                  datasetParentName: pool-0/k8s/nfs/volumes
                  detachedSnapshotsDatasetParentName: pool-0/k8s/nfs/snapshots
                  datasetEnableQuotas: true
                  datasetEnableReservation: false
                  datasetPermissionsMode: "0777"
                  datasetPermissionsUser: 0
                  datasetPermissionsGroup: 0
                nfs:
                  shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
                  shareHost: 10.0.40.9
                  shareAlldirs: true
                  shareAllowedHosts: []
                  shareAllowedNetworks: []
                  shareMaprootUser: root
                  shareMaprootGroup: wheel
                  shareMapallUser: ""
                shareMapallGroup: ""
  syncPolicy:
    automated:
      prune: true
      selfHeal: true