---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: rook-ceph
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  sources:
    - repoURL: https://github.com/prrlvr/infra.git
      targetRevision: HEAD
      path: kubernetes/apps/k8s/rook-ceph-operator
    - repoURL: https://charts.rook.io/release
      chart: rook-ceph
      targetRevision: v1.16.6
      helm:
        releaseName: rook-ceph
        valuesObject:
          monitoring:
            enabled: true